routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * to make new conttoller command
php artisan make:controller Frontend/IndexController --resource
*/

use Illuminate\Support\Facades\Route;

//Auth::routes();


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
    ->group(function () {

        Route::middleware('auth:admin')->group(function () {
            //write your routes for backend
            Route::get('/', 'DashboardController@index')->name('dashboard');
//        products route
            Route::get('/products', 'ProductController@index')->name('product.list');
            Route::get('/product-add', 'ProductController@create')->name('product.add');
            Route::get('/product-edit/{id}', 'ProductController@edit')->name('product.edit');
//        product create
            Route::post('/product-create', 'ProductController@store')->name('product.create');
            Route::post('/product-update', 'ProductController@update')->name('product.update');
            Route::post('/product-destroy', 'ProductController@destroy')->name('product.destroy');


//        category route
            Route::get('/category', 'CategoryController@index')->name('category.list');
            Route::get('/category-add', 'CategoryController@create')->name('category.add');
            Route::post('/category-create', 'CategoryController@store')->name('category.create');
            Route::get('/category-edit/{id}', 'CategoryController@edit')->name('category.edit');
            Route::post('/category-update', 'CategoryController@update')->name('category.update');
            Route::get('/category_slug', 'CategoryController@check_slug')->name('category.slug');
            Route::post('/category-destroy', 'CategoryController@destroy')->name('category.destroy');

//        Order's route
            Route::get('/order', 'OrderController@index')->name('order.list');
            Route::get('/order/{id}', 'OrderController@show')->name('order.show');
            Route::get('/order-edit/{id}', 'OrderController@edit')->name('order.edit');
            Route::post('/order-update', 'OrderController@update')->name('order.update');
            Route::get('/pdf/{id}', 'OrderController@pdf')->name('order.pdf');


//        Slider route
            Route::get('/slider', 'SliderController@index')->name('slider.list');
            Route::get('/slider-add', 'SliderController@create')->name('slider.add');
            Route::post('/slider-create', 'SliderController@store')->name('slider.create');
            Route::get('/slider-edit/{id}', 'SliderController@edit')->name('slider.edit');
            Route::post('/slider-update', 'SliderController@update')->name('slider.update');
            Route::post('/slider-destroy', 'SliderController@destroy')->name('slider.destroy');

//        coupon route
            Route::get('coupon', 'CouponController@index')->name('coupon.list');
            Route::get('coupon/new', 'CouponController@new')->name('coupon.add');
            Route::post('coupon/create', 'CouponController@create')->name('coupon.create');
            Route::get('coupon/edit/{id}', 'CouponController@edit')->name('coupon.edit');
            Route::post('coupon/update', 'CouponController@update')->name('coupon.update');
            Route::post('coupon/destroy', 'CouponController@destroy')->name('coupon.destroy');

//        reviews controller for admin
            Route::get('reviews', 'AdminReviewController@index')->name('reviews.list');
            Route::get('reviews/show/{id}', 'AdminReviewController@show')->name('reviews.show');
            Route::post('/review-destroy', 'AdminReviewController@destroy')->name('reviews.destroy');


            //        Fetured Categories route
            Route::get('/featuredcategories', 'FeaturedCategoryController@index')->name('featuredcategories.list');
            Route::get('/featuredcategories-add', 'FeaturedCategoryController@create')->name('featuredcategories.add');
            Route::post('/featuredcategories-create', 'FeaturedCategoryController@store')->name('featuredcategories.create');
            Route::get('/featuredcategories-edit/{id}', 'FeaturedCategoryController@edit')->name('featuredcategories.edit');
            Route::post('/featuredcategories-update', 'FeaturedCategoryController@update')->name('featuredcategories.update');
            Route::post('/featuredcategories-destroy', 'FeaturedCategoryController@destroy')->name('featuredcategories.destroy');

//        sales report
            Route::get('/sales-report', 'ReportController@index')->name('report.index');

            Route::get('/settings', 'SettingsController@index')->name('settings.index');
            Route::post('/settings', 'SettingsController@update')->name('settings.update');

            Route::get('/feedback', 'FeedbackController@index')->name('feedback.list');
            Route::get('/feedback/{id}', 'FeedbackController@show')->name('feedback.show');
            Route::post('/feedback-destroy', 'FeedbackController@destroy')->name('feedback.destroy');

            Route::get('/newsletter', 'NewsletterController@index')->name('newsletter.index');
            Route::post('/newsletter-destroy', 'NewsletterController@destroy')->name('newsletter.destroy');

            Route::get('/users', 'UserController@index')->name('user.list');
             Route::get('/user-edit/{id}', 'UserController@edit')->name('user.edit');

            Route::post('/user-update', 'UserController@update')->name('user.update');
            Route::post('/user-destroy', 'UserController@destroy')->name('user.destroy');

            Route::get('/notification', 'NotificationController@index')->name('notification');
            Route::post('/notification-create', 'NotificationController@sendNotification')->name('notification.create');

        });


        Route::get('/login', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'showLoginForm'])->name('login');
        Route::get('/register', [App\Http\Controllers\Backend\Auth\RegisterController::Class, 'showAdminRegisterForm'])->name('register');
        Route::get('/password', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'showAdminLoginForm'])->name('password.request');
        Route::post('/login/', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'login'])->name('login.create');
        Route::post('/register', [App\Http\Controllers\Backend\Auth\RegisterController::Class, 'createAdmin'])->name('register.create');
        Route::post('/logout', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'logout'])->name('logout');
//        for slug generation
        Route::get('/check_slug', 'ProductController@check_slug')->name('product.slug');


    });


Route::name('frontend.')
    ->namespace('Frontend')
    ->group(function () {


        Route::get('/login', [App\Http\Controllers\Frontend\Auth\LoginController::Class, 'showUserLoginForm'])->name('login');
        Route::get('/register', [App\Http\Controllers\Frontend\Auth\RegisterController::Class, 'showUserRegisterForm'])->name('register');
        Route::get('/password', [App\Http\Controllers\Frontend\Auth\LoginController::Class, 'showUserLoginForm'])->name('password.request');
        Route::post('/login/', [App\Http\Controllers\Frontend\Auth\LoginController::Class, 'userLogin'])->name('login.create');
        Route::post('/register', [App\Http\Controllers\Frontend\Auth\RegisterController::Class, 'createUser'])->name('register.create');
        Route::post('/logout', [App\Http\Controllers\Frontend\Auth\LogoutController::Class, 'userLogout'])->name('logout');


        //write your routes for frontend
        Route::get('/', 'IndexController@index')->name('index');


        // shop route
        Route::get('/shop/{product}', 'ShopController@show')->name('shop.show');
        Route::get('/shop', 'ShopController@index')->name('shop.index');

        // cart route

        Route::get('/cart', 'CartController@index')->name('cart.index');
        Route::post('/cart', 'CartController@store')->name('cart.store');
        Route::get('/cart/{product}', 'CartController@destroy')->name('cart.destroy');
        Route::post('/cart/{product}', 'CartController@update')->name('cart.update');


        ///wish list

        Route::post('/wishlist', 'WishlistController@store')->name('wishlist.store');
        Route::get('/wishlist', 'WishlistController@index')->name('wishlist.index');
        Route::get('/wishlist/{product}', 'WishlistController@destroy')->name('wishlist.destroy');

        //checkout
        Route::get('/checkout', 'CheckoutController@index')->name('checkout.index')->middleware('auth:user');
        Route::post('/checkout', 'CheckoutController@store')->name('checkout.store')->middleware('auth:user');

        // coupon route
        Route::post('/coupon', 'CartController@storeCoupon')->name('coupon.store');
        Route::delete('/coupon', 'CartController@destroyCoupon')->name('coupon.destroy');

        //        review
        Route::post('/review-add', 'ReviewController@store')->name('review.store');
//        newsletter
        Route::post('/newsletter-add', 'IndexController@newsletter')->name('newsletter.add');
        Route::post('/feedback-add', 'IndexController@feedback')->name('feedback.add');


        //my accout

        Route::get('/my-account', 'OrderIndexController@index')->name('my-account')->middleware('auth:user');
        Route::post('/my-account', 'OrderIndexController@store')->name('my-account.store')->middleware('auth:user');

        // password update

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\CancelReason;
use App\Order;
use App\OrderProduct;
use Barryvdh\DomPDF\Facade as PDF;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;
use MercurySeries\Flashy\Flashy;

class OrderController extends Controller
{

    public function index(Request $request ){

//        $orders = Order::orderBy('id', 'asc')->get();
//
//        return view('backend.pages.order.list')->with([
//            'orders' => $orders
//        ]);
        $orders = Order::where( function($query) use($request){
            return $request->status ?
                $query->from('status')->where('status',$request->status) : '';
        })->orderBy('created_at', 'asc')->get();

        //return $orders;
        return view('backend.pages.order.list')->with([
            'orders' => $orders
        ]);
    }

    public function filter(Request $request) {

        $orders = Order::where( function($query) use($request){
            return $request->status ?
                $query->from('status')->where('status',$request->status) : '';
        })->orderBy('id', 'asc')->get();

        return view('backend.pages.order.list')->with([
            'orders' => $orders
        ]);
    }
    public function create()
    {
        //
    }


    public function pdf($id) {
        $order = Order::find($id);
        $products = OrderProduct::select('order_products.quantity as amount', 'products.name as productName',
            'products.slug as slug','order_products.price as rate')
            ->join('products','order_products.product_id','=','products.id')
            ->where('order_products.order_id', $id)
            ->get();

        $invoice = substr(md5('muaj'.$id.'saif'), 0, 15) ;
        $invoice = $invoice.'.pdf';
        $pdf = PDF::loadView('backend.pages.order.invoice', [
            'order' => $order,
            'products' => $products
        ]);

        return $pdf->stream('invoice_'.$invoice);
    }


    public function show($id) {

        $order = Order::find($id);

        $products = OrderProduct::select('order_products.quantity as amount', 'products.name as productName',
            'products.slug as slug','order_products.price as rate')
            ->join('products','order_products.product_id','=','products.id')
            ->where('order_products.order_id', $id)
            ->get();

        return view('backend.pages.order.show')->with([
            'order' => $order,
            'products' =>$products
        ]);
    }


    public function edit($id) {


        $order = Order::find($id);

        return view('backend.pages.order.edit')->with([
            'order' => $order
        ]);
    }

    public function update(Request $request)
    {

        $rules = [
            'status' => 'required',
            'town' => 'required',
            'city' => 'required',
            'address' => 'required',
            'email' => 'required',
            'number' => 'required',
            'reason' => 'required_if:status,Cancelled',

        ];

        $customMessages = [
        'reason.required_if' => 'You need to give a reason for canceling the order!'
        ];
        $this->validate($request, $rules, $customMessages);


        $order = Order::find($request->id);

        $order->status = $request->status;
        $order->billing_address = $request->address;
        $order->billing_town = $request->town;
        $order->billing_city = $request->city;
        $order->billing_zip_code = $request->zip;
        $order->billing_email = $request->email;
        $order->billing_phone_no = $request->number;
        if ( $request->status == "Cancelled"){
            $reason =  CancelReason::updateOrCreate(
                ['admin_id' =>  auth()->guard('admin')->user()->id],
                ['order_id' => $request->id]
            );
            $reason->order_id = $request->id;
            $reason->admin_id =  auth()->guard('admin')->user()->id;
            $reason->reasons =  $request->reason;
            $reason->save();
        }


        $order->save();


        if (strlen($request->number) == 11){
//            if($request->status == "Processing"){
//                $to= "88".$request->number;
//                $message = "Your DOOZO Order.......(".$order->id.") has been Received. Thanks.";
//                $return = json_decode( $this->sendSMS($to,$message ));
//
//                Flashy::success('Order update to '. $request->status .' SMS sent to : '.$to." Status : " .$return->message );
//            }
            if($request->status == "Cancelled"){
                $to= "88".$request->number;
                $message = "Your DOOZO Order.......(".$order->id.") has been Canceled, to know details please check on your app.";
                $return = json_decode( $this->sendSMS($to,$message ));

                Flashy::success('Order update to '. $request->status .' SMS sent to : '.$to." Status : " .$return->message );
            }
            if($request->status == "Shipped"){
                $to= "88".$request->number;
                $message = "Your DOOZO Order.......(".$order->id.") has been Shipped. Thanks.";
                $return = json_decode( $this->sendSMS($to,$message ));

                Flashy::success('Order update to '. $request->status .' SMS sent to : '.$to." Status : " .$return->message );
            }
            if($request->status == "Delivered"){
                $to= "88".$request->number;
                $message = "Your DOOZO Order.......(".$order->id.") has been Delivered. Thanks for Choosing DOOZO.";
                $return = json_decode( $this->sendSMS($to,$message ));

                Flashy::success('Order update to '. $request->status .' SMS sent to : '.$to." Status : " .$return->message );
            }
        }




       // Flashy::success('Order update to '. $request->status .' successful');
        return redirect()->route('backend.order.list');

    }


    public function destroy($id)
    {
        //
    }
    public function sendSMS($to, $message)
    {
        $curl = curl_init();
        $data =[
            "username"=> env('SMS_USERNAME'),
            "password"=>env('SMS_PASSWORD'),
            "sender"=> env('SMS_SENDER'),
            "message"=>$message,
            "to"=>$to
        ];
        curl_setopt_array($curl, array(
            CURLOPT_URL => "http://api.icombd.com/api/v2/sendsms/plaintext",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => json_encode($data),
            CURLOPT_HTTPHEADER => array(
                "Content-Type: application/json",
            ),
        ));
        $response = curl_exec($curl);
        $err = curl_error($curl);
        curl_close($curl);
        if ($err) {
          return $err;
        } else {
            return $response;
        }
    }

}

resources/views/backend/pages/order/list.blade.php
@extends('backend.layouts.app')

@section('title', 'Order statement')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Order's Report
{{--            <small>You can download as csv</small>--}}
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('backend.dashboard') }}"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li class="active">Order</li>
        </ol>
    </section>

    <div class="box">
        <div class="box-header">


            <div class="col-md-6 ">
{{--                <a href="#" class="btn btn-success">Download csv</a>--}}
            </div>
            <div class="col-md-6">

                <form action="{{ route('backend.order.list') }}" method="GET">
                    <div class="col-md-2">
                        <span> Order Status</span>
                    </div>

                    <div class="col-md-4">

                        <select  class="form-control" name="status" id="input">
                            <option value="">All</option>
                            <option value="Received" >Received</option>
                            <option   value="Processing" >Processing</option>
                            <option  value="Cancelled" style=" color: #b83400">Cancelled</option>
                            <option value="Shipped" style=" color: #00cc66">Shipped</option>
                            <option  value="Delivered" style=" color: #00cc66">Delivered</option>


                        </select>
                    </div>
                    <div class="col-md-6">
                        <input type="submit" class="btn btn-info " value="Filter">
                    </div>


                </form>
            </div>

        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="list" class="table table-bordered table-striped table-responsive table-hover" >
                <thead>
                <tr>
{{--                    <th>#</th>--}}
                    <th>Order ID</th>
                    <th>Email</th>
                    <th>City</th>
                    <th>Total Bill</th>

                    <th>Order time</th>
                    <th>Status</th>
                     <th>Action</th>
                </tr>
                </thead>
                <tbody>

                @foreach($orders->reverse() as $key=>$order)
                    <tr>
{{--                        <td>{{ $key+1 }}</td>--}}
                        <td>{{ $order->id }}</td>
                        <td>{{ $order->billing_email }}</td>
                        <td>{{ $order->billing_town }}, {{ $order->billing_city }}</td>
                        <td>{{ $order->billing_total }}</td>

                        <td>{{ date('F j, Y, g:i:s a', strtotime( $order->created_at) ) }}</td>
                                                <td>
                                                    @if($order->status == 'Received')
                                                        <span class=" badge alert-info">&nbsp; {{ $order->status }} &nbsp;</span>
                                                    @elseif($order->status == 'Cancelled')
                                                        <span class=" badge alert-error">&nbsp; {{ $order->status }} &nbsp;</span><br>
                                                        <span>{{empty($order->cancelReason)?"":$order->cancelReason->reasons}}</span>
                                                    @elseif($order->status == 'Processing')
                                                        <span class="badge alert-dark">&nbsp; {{ $order->status }} &nbsp;</span>
                                                    @elseif($order->status == 'Shipped')
                                                        <span class="badge alert-success">&nbsp; {{ $order->status }} &nbsp;</span>
                                                    @else($order->status == 'Delivered')
                                                        <span class="badge alert-success">&nbsp; {{ $order->status }} &nbsp;</span>
                                                    @endif
                                                </td>
                        <td>
                            <a href="{{ route('backend.order.show',['id'=> $order->id]) }}"><i class="fa fa-envelope-open fa-lg" style="color:dodgerblue" aria-hidden="true"></i> </a>&nbsp;&nbsp;
                            <a href="{{ route('backend.order.edit',['id'=> $order->id]) }}"><i class="fa fa-pencil-square fa-lg" style="color:forestgreen" aria-hidden="true"></i> </a>&nbsp;&nbsp;
                            {{--<a href=""><i class="fa fa-trash fa-lg deletebtn" data-id="{{ $order->id }}"--}}
                                          {{--data-name="{{ $order->mail }}" data-token="{{ @csrf_token() }}" style="color:red"></i> </a>--}}
                        </td>

                    </tr>
                @endforeach

                </tbody>
                <tfoot>
                <tr>

                    <th>Order ID</th>

                    <th>Email</th>
                    <th>City</th>
                    <th>Total Bill</th>

                    <th>Order time</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.box-body -->
    </div>



@endsection

@push('scripts')


    {{-- DataTable js --}}
    <link rel="stylesheet" href="{{asset('backend/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <script src="{{asset('backend/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{asset('backend/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script>
        $(function () {
            $('#list').DataTable({
                "order": [[ 0, "desc" ]]
            });

            $('.order').addClass('active');
        });

    </script>
@endpush

resources/views/backend/pages/order/show.blade.php
@extends('backend.layouts.app')

@section('title', 'Order detail')

@section('content')
    <section class="content-header">
        <h1>
            Order's Detail
            <small> </small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('backend.dashboard') }}"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li><a href="{{ route('backend.order.list') }}"><i class="fa fa-dashboard"></i> Order</a></li>
            <li class="active">Order Detail</li>
        </ol>
    </section>

    <!-- Content Wrapper. Contains page content -->
    <div class="content ">
        <!-- this row will not appear when printing -->
        <div class="row no-print">
            <div class="col-xs-12">
                <a href="{{ route('backend.order.pdf',['id' => $order->id]) }}" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Print</a>

                <a href="{{ route('backend.order.pdf',['id' => $order->id]) }}" class="btn btn-primary pull-right" style="margin-right: 5px;">
                    <i class="fa fa-download"></i> Generate PDF
                </a>

            </div>
        </div>

        {{--<div class="pad margin no-print">--}}
            {{--<div class="callout callout-info" style="margin-bottom: 0!important;">--}}
                {{--<h4><i class="fa fa-info"></i> Note:</h4>--}}
                {{--This page has been enhanced for printing. Click the print button at the bottom of the invoice to test.--}}
            {{--</div>--}}
        {{--</div>--}}

        <!-- Main content -->
        <section class="invoice">
            <!-- title row -->
            <div class="row">
                <div class="col-xs-12">
                    <h2 class="page-header">
                        <i class="fa fa-gflobe"></i>
                        <small class="pull-right">Date: {{ date('F j, Y, g:i:s a', strtotime( $order->created_at)) }}</small>
                    </h2>
                </div>
                <!-- /.col -->
            </div>
            <!-- info row -->
            <div class="row invoice-info">

                <div class="col-sm-4 invoice-col">
                    To
                    <address>
                        <strong>{{ $order->billing_first_name }} {{ $order->billing_last_name }}</strong><br>
                        {{ $order->billing_address }}<br>
                        {{ $order->billing_town }}, {{ $order->billing_city}} &nbsp;
                        {{ $order->billing_zip_code }} <br>
                        Phone: {{ $order->billing_phone_no }}<br>
                        Email: {{ $order->billing_email }}
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                    <b>Order ID # {{ $order->id  }}</b><br>
                    <br>
                    <b>Shipping tracker no:</b> {{$order->shipping->tracker}}<br>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->

            <!-- Table row -->
            <div class="row">
                <div class="col-xs-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Product Name</th>
                            <th>Product slug</th>
                            <th>Qty</th>
                            <th>Rate</th>
                            <th>Subtotal</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($products as $product)
                        <tr>
                            <td>{{ $product->productName }}</td>
                            <td> <a href="{{ route('frontend.shop.show',['id'=> $product->slug]) }}">
                                    {{ $product->productName }} </a></td>
                            <td>{{ $product->amount }}</td>
                            <td>{{ $product->rate }} ৳</td>
                            <td>{{ $product->rate * $product->amount }} ৳</td>

                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->

            <div class="row">
                <!-- accepted payments column -->
                <div class="col-xs-6">
                    <p class="lead">Payment Methods:</p>
                    <p>Payer name: {{ $order->billing_first_name }} {{ $order->billing_last_name }}</p>


                    <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                         Payment Method: {{ $order->billing_payment_gateway }} <br>
                         Amount to Pay: {{ $order->billing_total }} ৳<br>

                    </p>
                </div>
                <!-- /.col -->
                <div class="col-xs-6">

                    <div class="table-responsive">
                        <table class="table">
                            <tr>
                                <th style="width:50%">Subtotal:</th>
                                <td>{{ $order->billing_subtotal }} ৳</td>
                            </tr>
                            <tr>
                                <th>Shipping:</th>
                                <td>{{ $order->billing_shipping_fee }} ৳</td>
                            </tr>
                            <tr>
                                <th>Promo:</th>
                                <td>-{{ $order->billing_discount }} ৳ {{empty($order->billing_discount_code) ? "" : " (".$order->billing_discount_code.") "}}</td>
                            </tr>
                            <tr>
                                <th>Total:</th>
                                <td>{{ $order->billing_total }} ৳</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /.row -->
            <!-- /.box-body -->
            <div class="box-footer">
                <a href="{{  route('backend.order.list') }}" class="btn btn-info">Cancel</a>
            </div>
            <!-- /.box-footer -->

        </section>
        <!-- /.content -->
        <div class="clearfix"></div>
    </div>
    <!-- /.content-wrapper -->


@endsection