routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * to make new conttoller command
php artisan make:controller Frontend/IndexController --resource
*/

use Illuminate\Support\Facades\Route;

//Auth::routes();


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
    ->group(function () {

        Route::middleware('auth:admin')->group(function () {
            //write your routes for backend
            Route::get('/', 'DashboardController@index')->name('dashboard');
//        products route
            Route::get('/products', 'ProductController@index')->name('product.list');
            Route::get('/product-add', 'ProductController@create')->name('product.add');
            Route::get('/product-edit/{id}', 'ProductController@edit')->name('product.edit');
//        product create
            Route::post('/product-create', 'ProductController@store')->name('product.create');
            Route::post('/product-update', 'ProductController@update')->name('product.update');
            Route::post('/product-destroy', 'ProductController@destroy')->name('product.destroy');


//        category route
            Route::get('/category', 'CategoryController@index')->name('category.list');
            Route::get('/category-add', 'CategoryController@create')->name('category.add');
            Route::post('/category-create', 'CategoryController@store')->name('category.create');
            Route::get('/category-edit/{id}', 'CategoryController@edit')->name('category.edit');
            Route::post('/category-update', 'CategoryController@update')->name('category.update');
            Route::get('/category_slug', 'CategoryController@check_slug')->name('category.slug');
            Route::post('/category-destroy', 'CategoryController@destroy')->name('category.destroy');

//        Order's route
            Route::get('/order', 'OrderController@index')->name('order.list');
            Route::get('/order/{id}', 'OrderController@show')->name('order.show');
            Route::get('/order-edit/{id}', 'OrderController@edit')->name('order.edit');
            Route::post('/order-update', 'OrderController@update')->name('order.update');
            Route::get('/pdf/{id}', 'OrderController@pdf')->name('order.pdf');


//        Slider route
            Route::get('/slider', 'SliderController@index')->name('slider.list');
            Route::get('/slider-add', 'SliderController@create')->name('slider.add');
            Route::post('/slider-create', 'SliderController@store')->name('slider.create');
            Route::get('/slider-edit/{id}', 'SliderController@edit')->name('slider.edit');
            Route::post('/slider-update', 'SliderController@update')->name('slider.update');
            Route::post('/slider-destroy', 'SliderController@destroy')->name('slider.destroy');

//        coupon route
            Route::get('coupon', 'CouponController@index')->name('coupon.list');
            Route::get('coupon/new', 'CouponController@new')->name('coupon.add');
            Route::post('coupon/create', 'CouponController@create')->name('coupon.create');
            Route::get('coupon/edit/{id}', 'CouponController@edit')->name('coupon.edit');
            Route::post('coupon/update', 'CouponController@update')->name('coupon.update');
            Route::post('coupon/destroy', 'CouponController@destroy')->name('coupon.destroy');

//        reviews controller for admin
            Route::get('reviews', 'AdminReviewController@index')->name('reviews.list');
            Route::get('reviews/show/{id}', 'AdminReviewController@show')->name('reviews.show');
            Route::post('/review-destroy', 'AdminReviewController@destroy')->name('reviews.destroy');


            //        Fetured Categories route
            Route::get('/featuredcategories', 'FeaturedCategoryController@index')->name('featuredcategories.list');
            Route::get('/featuredcategories-add', 'FeaturedCategoryController@create')->name('featuredcategories.add');
            Route::post('/featuredcategories-create', 'FeaturedCategoryController@store')->name('featuredcategories.create');
            Route::get('/featuredcategories-edit/{id}', 'FeaturedCategoryController@edit')->name('featuredcategories.edit');
            Route::post('/featuredcategories-update', 'FeaturedCategoryController@update')->name('featuredcategories.update');
            Route::post('/featuredcategories-destroy', 'FeaturedCategoryController@destroy')->name('featuredcategories.destroy');

//        sales report
            Route::get('/sales-report', 'ReportController@index')->name('report.index');

            Route::get('/settings', 'SettingsController@index')->name('settings.index');
            Route::post('/settings', 'SettingsController@update')->name('settings.update');

            Route::get('/feedback', 'FeedbackController@index')->name('feedback.list');
            Route::get('/feedback/{id}', 'FeedbackController@show')->name('feedback.show');
            Route::post('/feedback-destroy', 'FeedbackController@destroy')->name('feedback.destroy');

            Route::get('/newsletter', 'NewsletterController@index')->name('newsletter.index');
            Route::post('/newsletter-destroy', 'NewsletterController@destroy')->name('newsletter.destroy');

            Route::get('/users', 'UserController@index')->name('user.list');
             Route::get('/user-edit/{id}', 'UserController@edit')->name('user.edit');

            Route::post('/user-update', 'UserController@update')->name('user.update');
            Route::post('/user-destroy', 'UserController@destroy')->name('user.destroy');

            Route::get('/notification', 'NotificationController@index')->name('notification');
            Route::post('/notification-create', 'NotificationController@sendNotification')->name('notification.create');

        });


        Route::get('/login', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'showLoginForm'])->name('login');
        Route::get('/register', [App\Http\Controllers\Backend\Auth\RegisterController::Class, 'showAdminRegisterForm'])->name('register');
        Route::get('/password', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'showAdminLoginForm'])->name('password.request');
        Route::post('/login/', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'login'])->name('login.create');
        Route::post('/register', [App\Http\Controllers\Backend\Auth\RegisterController::Class, 'createAdmin'])->name('register.create');
        Route::post('/logout', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'logout'])->name('logout');
//        for slug generation
        Route::get('/check_slug', 'ProductController@check_slug')->name('product.slug');


    });


Route::name('frontend.')
    ->namespace('Frontend')
    ->group(function () {


        Route::get('/login', [App\Http\Controllers\Frontend\Auth\LoginController::Class, 'showUserLoginForm'])->name('login');
        Route::get('/register', [App\Http\Controllers\Frontend\Auth\RegisterController::Class, 'showUserRegisterForm'])->name('register');
        Route::get('/password', [App\Http\Controllers\Frontend\Auth\LoginController::Class, 'showUserLoginForm'])->name('password.request');
        Route::post('/login/', [App\Http\Controllers\Frontend\Auth\LoginController::Class, 'userLogin'])->name('login.create');
        Route::post('/register', [App\Http\Controllers\Frontend\Auth\RegisterController::Class, 'createUser'])->name('register.create');
        Route::post('/logout', [App\Http\Controllers\Frontend\Auth\LogoutController::Class, 'userLogout'])->name('logout');


        //write your routes for frontend
        Route::get('/', 'IndexController@index')->name('index');


        // shop route
        Route::get('/shop/{product}', 'ShopController@show')->name('shop.show');
        Route::get('/shop', 'ShopController@index')->name('shop.index');

        // cart route

        Route::get('/cart', 'CartController@index')->name('cart.index');
        Route::post('/cart', 'CartController@store')->name('cart.store');
        Route::get('/cart/{product}', 'CartController@destroy')->name('cart.destroy');
        Route::post('/cart/{product}', 'CartController@update')->name('cart.update');


        ///wish list

        Route::post('/wishlist', 'WishlistController@store')->name('wishlist.store');
        Route::get('/wishlist', 'WishlistController@index')->name('wishlist.index');
        Route::get('/wishlist/{product}', 'WishlistController@destroy')->name('wishlist.destroy');

        //checkout
        Route::get('/checkout', 'CheckoutController@index')->name('checkout.index')->middleware('auth:user');
        Route::post('/checkout', 'CheckoutController@store')->name('checkout.store')->middleware('auth:user');

        // coupon route
        Route::post('/coupon', 'CartController@storeCoupon')->name('coupon.store');
        Route::delete('/coupon', 'CartController@destroyCoupon')->name('coupon.destroy');

        //        review
        Route::post('/review-add', 'ReviewController@store')->name('review.store');
//        newsletter
        Route::post('/newsletter-add', 'IndexController@newsletter')->name('newsletter.add');
        Route::post('/feedback-add', 'IndexController@feedback')->name('feedback.add');


        //my accout

        Route::get('/my-account', 'OrderIndexController@index')->name('my-account')->middleware('auth:user');
        Route::post('/my-account', 'OrderIndexController@store')->name('my-account.store')->middleware('auth:user');

        // password update

app/Category.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use Sluggable;

    public function sluggable() {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use App\Product;
use Cviebrock\EloquentSluggable\Services\SlugService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Storage;
use MercurySeries\Flashy\Flashy;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Foundation\Application|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        $categories = Category::all();

        return view('backend.pages.category.list')->with([
            'categories' => $categories
        ]);
    }

    public function check_slug(Request $request){
        $slug = SlugService::createSlug(Category::class, 'slug',$request->categoryName);

        return response()->json(['slug' => $slug]);
    }

    public function create() {
        return view('backend.pages.category.add');
    }

    public function store(Request $request)
    {

        $rules = [
            'categoryName' => 'required',
            'categorySlug' => 'required',
        ];

        $customMessages = [
//            'name.required' => 'Yo, what should I call you?',
//            'email.required' => 'We need your email address also',
        ];
        $this->validate($request, $rules, $customMessages);
        $catThumbImg="";
        $cat = new Category();

        $cat->name = $request->categoryName;
//        slug auto generate

        $photo_productThumbImg = $request->file('categoryThumbImg');

        if (isset($photo_productThumbImg)){
            if ($photo_productThumbImg->isValid()){
                $file_name =
                    uniqid('thumb_',true).str_random(5).'.'.$photo_productThumbImg->getClientOriginalExtension();
                $catThumbImg = $photo_productThumbImg->storeAs('categories',$file_name);

            }

        }
        $cat->banner = $catThumbImg;
        $cat->save();

        Flashy::success('Category '. $request->categoryName.' created.');

        return redirect()->route('backend.category.list');
    }


    public function show($id)
    {
        //
    }


    public function edit($id) {


        $category = Category::where('id', $id)->firstOrFail();

        return view('backend.pages.category.edit')->with([
            'category' => $category
        ]);
    }


    public function update(Request $request)
    {
        $rules = [
            'categoryName' => 'required',
            'categorySlug' => 'required|alpha_dash|unique:categories,slug,'.$request->id,
        ];

        $customMessages = [
//            'name.required' => 'Yo, what should I call you?',
//            'email.required' => 'We need your email address also',
        ];
        $this->validate($request, $rules, $customMessages);

        $category = Category::find($request->id);

        $category->name = $request->categoryName;
        $category->slug = $request->categorySlug;




        if($request->categoryThumbImg){
            $photo_productThumbImg = $request->file('categoryThumbImg');
            $file_name =
                uniqid('thumb_',true).str_random(5).'.'.$photo_productThumbImg->getClientOriginalExtension();

            if ($photo_productThumbImg->isValid()){
                $productThumbImg =$photo_productThumbImg->storeAs('categories',$file_name);
            }
            Storage::delete( $category->banner);
            $category->banner= $productThumbImg;
        }
        $category->save();

        Flashy::success('Category updated.');


        return $this->index();
    }



    public function destroy(Request $request) {
        Category::find($request->id)->delete();

        Flashy::error('Category deleted');
        return redirect()->route('backend.category.list');

    }
}

resources/views/backend/pages/category/add.blade.php
@extends('backend.layouts.app')

@section('title', 'Add Category')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            New Category
            <small>Create a new category</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li><a href="#"><i class="fa fa-bandcamp"></i> Category</a></li>
            <li class="active">New Category</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content container-fluid">

        <div class="product">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <!-- form start -->
                <form class="form-horizontal" action="{{ route('backend.category.create') }}" method="post"
                      enctype="multipart/form-data">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">

                            <label for="inputCategoryName" class="col-sm-2 control-label">Category Name</label>

                            <div class="col-sm-6">
                                <input  required type="text" class="form-control" id="inputCategoryName" name="categoryName" placeholder="New Category.." >
                                @if ($errors->has('categoryName'))
                                    <span class="text-red" >
                                        <strong>{{ $errors->first('categoryName') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">

                        <label for="inputCatSlug" class="col-sm-2 control-label">Slug</label>

                            <div class="col-sm-6">
                                <input required type="text" class="form-control" id="inputCatSlug" name="categorySlug" placeholder="Slug (auto generate)" >
                                @if ($errors->has('categorySlug'))
                                    <span class="text-red">
                                        <strong>{{ $errors->first('categorySlug') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="thumbImg" class="col-sm-2 control-label">Thumbnail Image</label>

                            <div class="col-sm-6">
                                <input type="file" class="form-control" id="thumbImg" name="categoryThumbImg">
                            </div>
                        </div>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a href="{{ url()->previous() }}" class="btn btn-default">Cancel</a>
                        <button type="submit" class="btn btn-info pull-right">Create</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
            <!-- /.box -->
        </div>

    </section>
    <!-- /.content -->


@endsection


@section('script')
    <script>
        $('#inputCategoryName').on('input',function (e) {
            console.log($(this).val());
            $.get('{{ route('backend.category.slug') }}',
                { 'categoryName' : $(this).val() },
                function (data) {
                    $('#inputCatSlug').val(data.slug);
                }
            );

        });
        </script>

@endsection

resources/views/backend/pages/category/edit.blade.php
@extends('backend.layouts.app')

@section('title', 'Edit Category')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
             Category
            <small>Edit Category</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li><a href="#"><i class="fa fa-bandcamp"></i> Category</a></li>
            <li class="active">Edit Category</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content container-fluid">

        <div class="product">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <!-- form start -->
                <form class="form-horizontal" action="{{ route('backend.category.update') }}" method="post"  enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" class="form-control"  name="id" value="{{ $category->id }}" >

                    <div class="box-body">
                        <div class="form-group">

                            <label for="inputCategoryName" class="col-sm-2 control-label">Category Name</label>

                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="inputCategoryName" name="categoryName" value="{{ $category->name }}" required>

                                @if ($errors->has('categoryName'))
                                    <span class="text-red" >
                                        <strong>{{ $errors->first('categoryName') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">

                            <label for="inputCatSlug" class="col-sm-2 control-label">Slug</label>

                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="inputCatSlug" name="categorySlug" value="{{ $category->slug }}" required>
                                @if ($errors->has('categorySlug'))
                                    <span class="text-red">
                                        <strong>{{ $errors->first('categorySlug') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="thumbImg" class="col-sm-2 control-label">Thumbnail Image</label>

                            <div class="col-sm-6">
                                <img height=500 width=500 src="{{ !empty($category->banner)? asset('uploads/'.$category->banner) : asset('backend/dist/img/not-found.jpg')  }}">

                                <input type="file" class="form-control" id="thumbImg" name="categoryThumbImg">
                            </div>
                        </div>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a href="{{ url()->previous() }}" class="btn btn-default">Cancel</a>
                        <button type="submit" class="btn btn-info pull-right">Create</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
            <!-- /.box -->
        </div>

    </section>
    <!-- /.content -->


@endsection


@section('script')
    <script>
        $('#inputCategoryName').on('input',function (e) {
            console.log($(this).val());
            $.get('{{ route('backend.category.slug') }}',
                { 'categoryName' : $(this).val() },
                function (data) {
                    $('#inputCatSlug').val(data.slug);
                }
            );

        });
    </script>

@endsection

resources/views/backend/pages/category/list.blade.php
@extends('backend.layouts.app')

@section('title', 'Category list')

@section('content')
    <section class="content-header">
        <h1>
            Category
            <small>Category list</small>
            <small>
                <a href="{{ route('backend.category.add') }}" class="btn btn-success">Add Category</a>
            </small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li><a href="#"><i class="fa fa-dashboard"></i> Category</a></li>
        </ol>
    </section>

    <div class="box">


        <!-- /.box-header -->
        <div class="box-body">
            <table id="category-list" class="table table-bordered table-striped table-responsive table-hover" >
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Banner</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $key => $category)
                <tr>
                <td>{{ $key+1 }}</td>
                <td>{{ $category->name }}</td>
                <td>{{ $category->slug }}</td>

                    <td>
                        <img height=100 width=100 src="{{ !empty($category->banner)? asset('uploads/'.$category->banner) : asset('backend/dist/img/not-found.jpg')  }}">
                    </td>

                <td >
{{--                <a href="#"><i class="fa fa-search-plus fa-lg" style="color:green" aria-hidden="true"></i> </a> &nbsp;--}}
                <a href="{{ route('backend.category.edit',['id'=> $category->id]) }}"><i class="fa fa-pencil-square fa-lg" style="color:dodgerblue" aria-hidden="true"></i> </a> &nbsp;
                    <a href=""><i class="fa fa-trash fa-lg deletebtn" data-id="{{ $category->id }}"
                                  data-name="{{ $category->name }}" data-token="{{ @csrf_token() }}" style="color:red"></i> </a>
                </td>

                </tr>
                @endforeach

                </tbody>
                <tfoot>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Banner</th>
                    <th>Action</th>
                </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.box-body -->
    </div>



@endsection

@push('scripts')
    {{-- DataTable js --}}
    <link rel="stylesheet" href="{{asset('backend/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <script src="{{asset('backend/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{asset('backend/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script>
        $(function () {
            $('#category-list').DataTable();
            $('.category').addClass('active');

        });
        $(document).on('click', '.deletebtn', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var token = $(this).data('token');
            var name = $(this).data('name');
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: "POST",
                        url: "{{ route('backend.category.destroy') }}",
                        data: {id:id, _token:token},
                        success: function (data) {
                            location.reload();
                        }
                    });

                    swal(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                }
            });

        });

    </script>

@endpush