routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * to make new conttoller command
php artisan make:controller Frontend/IndexController --resource
*/

use Illuminate\Support\Facades\Route;

//Auth::routes();


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
    ->group(function () {

        Route::middleware('auth:admin')->group(function () {
            //write your routes for backend
            Route::get('/', 'DashboardController@index')->name('dashboard');
//        products route
            Route::get('/products', 'ProductController@index')->name('product.list');
            Route::get('/product-add', 'ProductController@create')->name('product.add');
            Route::get('/product-edit/{id}', 'ProductController@edit')->name('product.edit');
//        product create
            Route::post('/product-create', 'ProductController@store')->name('product.create');
            Route::post('/product-update', 'ProductController@update')->name('product.update');
            Route::post('/product-destroy', 'ProductController@destroy')->name('product.destroy');


//        category route
            Route::get('/category', 'CategoryController@index')->name('category.list');
            Route::get('/category-add', 'CategoryController@create')->name('category.add');
            Route::post('/category-create', 'CategoryController@store')->name('category.create');
            Route::get('/category-edit/{id}', 'CategoryController@edit')->name('category.edit');
            Route::post('/category-update', 'CategoryController@update')->name('category.update');
            Route::get('/category_slug', 'CategoryController@check_slug')->name('category.slug');
            Route::post('/category-destroy', 'CategoryController@destroy')->name('category.destroy');

//        Order's route
            Route::get('/order', 'OrderController@index')->name('order.list');
            Route::get('/order/{id}', 'OrderController@show')->name('order.show');
            Route::get('/order-edit/{id}', 'OrderController@edit')->name('order.edit');
            Route::post('/order-update', 'OrderController@update')->name('order.update');
            Route::get('/pdf/{id}', 'OrderController@pdf')->name('order.pdf');


//        Slider route
            Route::get('/slider', 'SliderController@index')->name('slider.list');
            Route::get('/slider-add', 'SliderController@create')->name('slider.add');
            Route::post('/slider-create', 'SliderController@store')->name('slider.create');
            Route::get('/slider-edit/{id}', 'SliderController@edit')->name('slider.edit');
            Route::post('/slider-update', 'SliderController@update')->name('slider.update');
            Route::post('/slider-destroy', 'SliderController@destroy')->name('slider.destroy');

//        coupon route
            Route::get('coupon', 'CouponController@index')->name('coupon.list');
            Route::get('coupon/new', 'CouponController@new')->name('coupon.add');
            Route::post('coupon/create', 'CouponController@create')->name('coupon.create');
            Route::get('coupon/edit/{id}', 'CouponController@edit')->name('coupon.edit');
            Route::post('coupon/update', 'CouponController@update')->name('coupon.update');
            Route::post('coupon/destroy', 'CouponController@destroy')->name('coupon.destroy');

//        reviews controller for admin
            Route::get('reviews', 'AdminReviewController@index')->name('reviews.list');
            Route::get('reviews/show/{id}', 'AdminReviewController@show')->name('reviews.show');
            Route::post('/review-destroy', 'AdminReviewController@destroy')->name('reviews.destroy');


            //        Fetured Categories route
            Route::get('/featuredcategories', 'FeaturedCategoryController@index')->name('featuredcategories.list');
            Route::get('/featuredcategories-add', 'FeaturedCategoryController@create')->name('featuredcategories.add');
            Route::post('/featuredcategories-create', 'FeaturedCategoryController@store')->name('featuredcategories.create');
            Route::get('/featuredcategories-edit/{id}', 'FeaturedCategoryController@edit')->name('featuredcategories.edit');
            Route::post('/featuredcategories-update', 'FeaturedCategoryController@update')->name('featuredcategories.update');
            Route::post('/featuredcategories-destroy', 'FeaturedCategoryController@destroy')->name('featuredcategories.destroy');

//        sales report
            Route::get('/sales-report', 'ReportController@index')->name('report.index');

            Route::get('/settings', 'SettingsController@index')->name('settings.index');
            Route::post('/settings', 'SettingsController@update')->name('settings.update');

            Route::get('/feedback', 'FeedbackController@index')->name('feedback.list');
            Route::get('/feedback/{id}', 'FeedbackController@show')->name('feedback.show');
            Route::post('/feedback-destroy', 'FeedbackController@destroy')->name('feedback.destroy');

            Route::get('/newsletter', 'NewsletterController@index')->name('newsletter.index');
            Route::post('/newsletter-destroy', 'NewsletterController@destroy')->name('newsletter.destroy');

            Route::get('/users', 'UserController@index')->name('user.list');
             Route::get('/user-edit/{id}', 'UserController@edit')->name('user.edit');

            Route::post('/user-update', 'UserController@update')->name('user.update');
            Route::post('/user-destroy', 'UserController@destroy')->name('user.destroy');

            Route::get('/notification', 'NotificationController@index')->name('notification');
            Route::post('/notification-create', 'NotificationController@sendNotification')->name('notification.create');

        });


        Route::get('/login', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'showLoginForm'])->name('login');
        Route::get('/register', [App\Http\Controllers\Backend\Auth\RegisterController::Class, 'showAdminRegisterForm'])->name('register');
        Route::get('/password', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'showAdminLoginForm'])->name('password.request');
        Route::post('/login/', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'login'])->name('login.create');
        Route::post('/register', [App\Http\Controllers\Backend\Auth\RegisterController::Class, 'createAdmin'])->name('register.create');
        Route::post('/logout', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'logout'])->name('logout');
//        for slug generation
        Route::get('/check_slug', 'ProductController@check_slug')->name('product.slug');


    });


Route::name('frontend.')
    ->namespace('Frontend')
    ->group(function () {


        Route::get('/login', [App\Http\Controllers\Frontend\Auth\LoginController::Class, 'showUserLoginForm'])->name('login');
        Route::get('/register', [App\Http\Controllers\Frontend\Auth\RegisterController::Class, 'showUserRegisterForm'])->name('register');
        Route::get('/password', [App\Http\Controllers\Frontend\Auth\LoginController::Class, 'showUserLoginForm'])->name('password.request');
        Route::post('/login/', [App\Http\Controllers\Frontend\Auth\LoginController::Class, 'userLogin'])->name('login.create');
        Route::post('/register', [App\Http\Controllers\Frontend\Auth\RegisterController::Class, 'createUser'])->name('register.create');
        Route::post('/logout', [App\Http\Controllers\Frontend\Auth\LogoutController::Class, 'userLogout'])->name('logout');


        //write your routes for frontend
        Route::get('/', 'IndexController@index')->name('index');


        // shop route
        Route::get('/shop/{product}', 'ShopController@show')->name('shop.show');
        Route::get('/shop', 'ShopController@index')->name('shop.index');

        // cart route

        Route::get('/cart', 'CartController@index')->name('cart.index');
        Route::post('/cart', 'CartController@store')->name('cart.store');
        Route::get('/cart/{product}', 'CartController@destroy')->name('cart.destroy');
        Route::post('/cart/{product}', 'CartController@update')->name('cart.update');


        ///wish list

        Route::post('/wishlist', 'WishlistController@store')->name('wishlist.store');
        Route::get('/wishlist', 'WishlistController@index')->name('wishlist.index');
        Route::get('/wishlist/{product}', 'WishlistController@destroy')->name('wishlist.destroy');

        //checkout
        Route::get('/checkout', 'CheckoutController@index')->name('checkout.index')->middleware('auth:user');
        Route::post('/checkout', 'CheckoutController@store')->name('checkout.store')->middleware('auth:user');

        // coupon route
        Route::post('/coupon', 'CartController@storeCoupon')->name('coupon.store');
        Route::delete('/coupon', 'CartController@destroyCoupon')->name('coupon.destroy');

        //        review
        Route::post('/review-add', 'ReviewController@store')->name('review.store');
//        newsletter
        Route::post('/newsletter-add', 'IndexController@newsletter')->name('newsletter.add');
        Route::post('/feedback-add', 'IndexController@feedback')->name('feedback.add');


        //my accout

        Route::get('/my-account', 'OrderIndexController@index')->name('my-account')->middleware('auth:user');
        Route::post('/my-account', 'OrderIndexController@store')->name('my-account.store')->middleware('auth:user');

        // password update

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    //
    protected $fillable = ['title1','title2','detail','img','slug'];
}

app/Http/Controllers/Backend/SliderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Slider;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use MercurySeries\Flashy\Flashy;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $slider_list = Slider::all('id','title1','title2','detail','img','slug');
        return view('backend.pages.slider.list')->with([
            'sliders' => $slider_list
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {


        return view('backend.pages.slider.add');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'title1' => 'required',
            'title2' => 'required',
            'detail' => 'required',
            'slider' => 'required',
        ];

        $customMessages = [
//            'name.required' => 'Yo, what should I call you?',
//            'email.required' => 'We need your email address also',
        ];
        $this->validate($request, $rules, $customMessages);


        $sliderimg="";
        $photo_productG4 = $request->file('slider');
        if (isset($photo_productG4)) {
            if ($photo_productG4->isValid()){
                $file_name =
                    uniqid('slider_',true).str_random(5).'.'.$photo_productG4->getClientOriginalExtension();
                $sliderimg =$photo_productG4->storeAs('slider',$file_name);
            }
        }
        // create product with model method
           $slider =  new Slider();
          $slider->title1 = $request->title1;
           $slider->title2 = $request->title2;
           $slider->detail = $request->detail;
           $slider->slug = empty($request->slug) ? "#" :$request->slug ;
        $slider->img = $sliderimg;

        $slider->save();



        Flashy::success('Slider created.');

//        return view('backend.pages.product.list');
        return redirect()->route('backend.slider.list');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

        $slider = Slider::where('id',$id)->firstOrFail();


        return view('backend.pages.slider.edit')->with([
            'slider' => $slider,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $rules = [
            'title1' => 'required',
            'title2' => 'required',
            'detail' => 'required',
        ];

        $customMessages = [
//            'name.required' => 'Yo, what should I call you?',
//            'email.required' => 'We need your email address also',
        ];
        $this->validate($request, $rules, $customMessages);
        $slider =  Slider::find($request->id);

        $sliderimg="";
        $photo_productG4 = $request->file('slider');
        if (isset($photo_productG4)) {
            if ($photo_productG4->isValid()){
                $file_name =
                    uniqid('slider_',true).str_random(5).'.'.$photo_productG4->getClientOriginalExtension();
                $sliderimg =$photo_productG4->storeAs('slider',$file_name);
                $slider->img = $sliderimg;

            }
        }
        // create product with model method
        $slider->title1 = $request->title1;
        $slider->title2 = $request->title2;
        $slider->detail = $request->detail;
        $slider->slug = empty($request->slug) ? "#" :$request->slug ;
        $slider->save();



        Flashy::success('Slider updated.');

//        return view('backend.pages.product.list');
        return redirect()->route('backend.slider.list');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        //
        Slider::find($request->id)->delete();

        return redirect()->route('backend.slider.list');
    }
}

resources/views/backend/pages/slider/add.blade.php
@extends('backend.layouts.app')
@section('title' , 'New Slider')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            New Slider
            <small>Create a new Slider</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li class="active">New Slider</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">

        <div class="product">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <!-- form start -->
                <form class="form-horizontal" action="{{ route('backend.slider.create') }}" method="post"
                 enctype="multipart/form-data">
                    @csrf
                    <div class="box-body">
                        <div class="form-group">

                            <label for="inputTitle1" class="col-sm-2 control-label">Title 1</label>

                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="inputTitle1" name="title1" placeholder="Title 1.." required>
                            </div>


                        </div>
                        <div class="form-group">

                            <label for="inputTitle2" class="col-sm-2 control-label">Title 2</label>

                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="inputTitle2" name="title2" placeholder="Title 2.." required>
                            </div>

                        </div>
                        <div class="form-group">
                            <label for="inputDetail" class="col-sm-2 control-label">Details</label>

                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputDetail" name="detail" placeholder="Details" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="sliderImg" class="col-sm-2 control-label">Slider Image</label>

                            <div class="col-sm-4">
                                <input type="file" class="form-control" id="sliderImg" placeholder="Slider Image" name="slider">
                            </div>
                            <label for="slug" class="col-sm-2 control-label ">Slug</label>

                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="slug" name="slug" placeholder="Slug">
                            </div>
                        </div>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a href="{{ url()->previous() }}" class="btn btn-default">Cancel</a>
                        <button type="submit" class="btn btn-info pull-right">Create</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
            <!-- /.box -->
        </div>

    </section>
    <!-- /.content -->

@endsection

resources/views/backend/pages/slider/edit.blade.php
@extends('backend.layouts.app')

@section('title' , 'Edit > '. $slider->name )

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Update slider info
            <small>{{ $slider->name }} </small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('backend.dashboard') }}"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li><a href=" {{ route('backend.slider.list') }}"><i class="fa fa-shopping-cart"></i> Slider</a></li>
            <li class="active">Edit Slider</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">

        <div class="product">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <!-- form start -->
                <form class="form-horizontal" action="{{ route('backend.slider.update') }}" method="post"
                      enctype="multipart/form-data">
                    @csrf

                    <input type="hidden" class="form-control" id="inputTitle1" name="id" value="{{ $slider->id }}" required>

                    <div class="box-body">
                        <div class="form-group">

                            <label for="inputTitle1" class="col-sm-2 control-label">Title 1</label>

                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="inputTitle1" name="title1" value="{{ $slider->title1 }}" required>
                            </div>


                        </div>
                        <div class="form-group">

                            <label for="inputTitle2" class="col-sm-2 control-label">Title 2</label>

                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="inputTitle2" name="title2" value="{{ $slider->title2 }}" required>
                            </div>

                        </div>
                        <div class="form-group">
                            <label for="inputDetail" class="col-sm-2 control-label">Details</label>

                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="inputDetail" name="detail" value="{{ $slider->detail }}" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="sliderImg" class="col-sm-2 control-label">Slider Image</label>

                            <div class="col-sm-4">
                                <input type="file" class="form-control" id="sliderImg" placeholder="Slider Image" name="slider">
                            </div>
                            <label for="slug" class="col-sm-2 control-label ">Slug</label>

                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="slug" name="slug" value="{{ $slider->slug }}">
                            </div>
                        </div>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a href="{{ url()->previous() }}" class="btn btn-default">Cancel</a>
                        <button type="submit" class="btn btn-info pull-right">Update</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
            <!-- /.box -->
        </div>


    </section>
    <!-- /.content -->

@endsection

@section('script')
    <script>
        $('#inputProductName').on('input',function (e) {
            // console.log($(this).val());
            $.get('{{ route('backend.product.slug') }}',
                { 'productName' : $(this).val() },
                function (data) {
                    $('#inputProductSlug').val(data.slug);
                }
            );

        });

        $(function () {
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace('inputDescription')
            //bootstrap WYSIHTML5 - text editor
            $('.textarea').wysihtml5()
        })
    </script>
@endsection

resources/views/backend/pages/slider/list.blade.php
@extends('backend.layouts.app')

@section('title', 'Slider list')

@section('content')

    <div class="box">
        <div class="box-header">
            <div class="col-md-3">
                <h3 class="box-title">Slider list</h3>
            </div>

            <div class="col-md-6 ">
                <a href="{{ route('backend.slider.add') }}" class="btn btn-success">Add Slider</a>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="product-list" class="table table-bordered table-striped table-responsive table-hover" >
                <thead>
                <tr>
                    <th>Title 1</th>
                    <th>Title 2</th>
                    <th>Detail</th>
                    <th>Image</th>
                    <th>Slug</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($sliders as $slider)
                <tr>
                    <td>{{ $slider->title1 }}</td>
                    <td>{{ $slider->title2 }}</td>
                    <td>{{ $slider->detail }}</td>
                    <td><img height=100 width=100 src="{{ asset('uploads/'.$slider->img)  }}"> </td>
                    <td>{{ $slider->slug }}</td>
                    <td>
                        <a href="{{ route('backend.slider.edit',['id'=> $slider->id]) }}"><i class="fa fa-pencil-square fa-lg" style="color:dodgerblue" aria-hidden="true"></i> </a>
                        <a href=""><i class="fa fa-trash fa-lg deletebtn" data-id="{{ $slider->id }}"
                                      data-name="{{ $slider->id }}" data-token="{{ @csrf_token() }}" style="color:red"></i> </a>
                    </td>

                </tr>
                @endforeach

                </tbody>
                <tfoot>
                <tr>
                    <th>Title 1</th>
                    <th>Title 2</th>
                    <th>Detail</th>
                    <th>Image</th>
                    <th>Slug</th>
                    <th>Action</th>
                </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.box-body -->
    </div>


@endsection


@push('scripts')


    {{-- DataTable js --}}
    <link rel="stylesheet" href="{{asset('backend/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <script src="{{asset('backend/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{asset('backend/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script>
        $(function () {
            $('#product-list').DataTable();
            $('.slider').addClass('active');

        });

        $(document).on('click', '.deletebtn', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var token = $(this).data('token');
            var name = $(this).data('name');
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",

                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: "POST",
                        url: "{{ route('backend.slider.destroy') }}",
                        data: {id:id, _token:token},
                        success: function (data) {
                            location.reload();
                        }
                    });

                    swal(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                }
            });

        });


    </script>
@endpush