routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
 * to make new conttoller command
php artisan make:controller Frontend/IndexController --resource
*/

use Illuminate\Support\Facades\Route;

//Auth::routes();


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
    ->group(function () {

        Route::middleware('auth:admin')->group(function () {
            //write your routes for backend
            Route::get('/', 'DashboardController@index')->name('dashboard');
//        products route
            Route::get('/products', 'ProductController@index')->name('product.list');
            Route::get('/product-add', 'ProductController@create')->name('product.add');
            Route::get('/product-edit/{id}', 'ProductController@edit')->name('product.edit');
//        product create
            Route::post('/product-create', 'ProductController@store')->name('product.create');
            Route::post('/product-update', 'ProductController@update')->name('product.update');
            Route::post('/product-destroy', 'ProductController@destroy')->name('product.destroy');


//        category route
            Route::get('/category', 'CategoryController@index')->name('category.list');
            Route::get('/category-add', 'CategoryController@create')->name('category.add');
            Route::post('/category-create', 'CategoryController@store')->name('category.create');
            Route::get('/category-edit/{id}', 'CategoryController@edit')->name('category.edit');
            Route::post('/category-update', 'CategoryController@update')->name('category.update');
            Route::get('/category_slug', 'CategoryController@check_slug')->name('category.slug');
            Route::post('/category-destroy', 'CategoryController@destroy')->name('category.destroy');

//        Order's route
            Route::get('/order', 'OrderController@index')->name('order.list');
            Route::get('/order/{id}', 'OrderController@show')->name('order.show');
            Route::get('/order-edit/{id}', 'OrderController@edit')->name('order.edit');
            Route::post('/order-update', 'OrderController@update')->name('order.update');
            Route::get('/pdf/{id}', 'OrderController@pdf')->name('order.pdf');


//        Slider route
            Route::get('/slider', 'SliderController@index')->name('slider.list');
            Route::get('/slider-add', 'SliderController@create')->name('slider.add');
            Route::post('/slider-create', 'SliderController@store')->name('slider.create');
            Route::get('/slider-edit/{id}', 'SliderController@edit')->name('slider.edit');
            Route::post('/slider-update', 'SliderController@update')->name('slider.update');
            Route::post('/slider-destroy', 'SliderController@destroy')->name('slider.destroy');

//        coupon route
            Route::get('coupon', 'CouponController@index')->name('coupon.list');
            Route::get('coupon/new', 'CouponController@new')->name('coupon.add');
            Route::post('coupon/create', 'CouponController@create')->name('coupon.create');
            Route::get('coupon/edit/{id}', 'CouponController@edit')->name('coupon.edit');
            Route::post('coupon/update', 'CouponController@update')->name('coupon.update');
            Route::post('coupon/destroy', 'CouponController@destroy')->name('coupon.destroy');

//        reviews controller for admin
            Route::get('reviews', 'AdminReviewController@index')->name('reviews.list');
            Route::get('reviews/show/{id}', 'AdminReviewController@show')->name('reviews.show');
            Route::post('/review-destroy', 'AdminReviewController@destroy')->name('reviews.destroy');


            //        Fetured Categories route
            Route::get('/featuredcategories', 'FeaturedCategoryController@index')->name('featuredcategories.list');
            Route::get('/featuredcategories-add', 'FeaturedCategoryController@create')->name('featuredcategories.add');
            Route::post('/featuredcategories-create', 'FeaturedCategoryController@store')->name('featuredcategories.create');
            Route::get('/featuredcategories-edit/{id}', 'FeaturedCategoryController@edit')->name('featuredcategories.edit');
            Route::post('/featuredcategories-update', 'FeaturedCategoryController@update')->name('featuredcategories.update');
            Route::post('/featuredcategories-destroy', 'FeaturedCategoryController@destroy')->name('featuredcategories.destroy');

//        sales report
            Route::get('/sales-report', 'ReportController@index')->name('report.index');

            Route::get('/settings', 'SettingsController@index')->name('settings.index');
            Route::post('/settings', 'SettingsController@update')->name('settings.update');

            Route::get('/feedback', 'FeedbackController@index')->name('feedback.list');
            Route::get('/feedback/{id}', 'FeedbackController@show')->name('feedback.show');
            Route::post('/feedback-destroy', 'FeedbackController@destroy')->name('feedback.destroy');

            Route::get('/newsletter', 'NewsletterController@index')->name('newsletter.index');
            Route::post('/newsletter-destroy', 'NewsletterController@destroy')->name('newsletter.destroy');

            Route::get('/users', 'UserController@index')->name('user.list');
             Route::get('/user-edit/{id}', 'UserController@edit')->name('user.edit');

            Route::post('/user-update', 'UserController@update')->name('user.update');
            Route::post('/user-destroy', 'UserController@destroy')->name('user.destroy');

            Route::get('/notification', 'NotificationController@index')->name('notification');
            Route::post('/notification-create', 'NotificationController@sendNotification')->name('notification.create');

        });


        Route::get('/login', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'showLoginForm'])->name('login');
        Route::get('/register', [App\Http\Controllers\Backend\Auth\RegisterController::Class, 'showAdminRegisterForm'])->name('register');
        Route::get('/password', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'showAdminLoginForm'])->name('password.request');
        Route::post('/login/', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'login'])->name('login.create');
        Route::post('/register', [App\Http\Controllers\Backend\Auth\RegisterController::Class, 'createAdmin'])->name('register.create');
        Route::post('/logout', [App\Http\Controllers\Backend\Auth\LoginController::Class, 'logout'])->name('logout');
//        for slug generation
        Route::get('/check_slug', 'ProductController@check_slug')->name('product.slug');


    });


Route::name('frontend.')
    ->namespace('Frontend')
    ->group(function () {


        Route::get('/login', [App\Http\Controllers\Frontend\Auth\LoginController::Class, 'showUserLoginForm'])->name('login');
        Route::get('/register', [App\Http\Controllers\Frontend\Auth\RegisterController::Class, 'showUserRegisterForm'])->name('register');
        Route::get('/password', [App\Http\Controllers\Frontend\Auth\LoginController::Class, 'showUserLoginForm'])->name('password.request');
        Route::post('/login/', [App\Http\Controllers\Frontend\Auth\LoginController::Class, 'userLogin'])->name('login.create');
        Route::post('/register', [App\Http\Controllers\Frontend\Auth\RegisterController::Class, 'createUser'])->name('register.create');
        Route::post('/logout', [App\Http\Controllers\Frontend\Auth\LogoutController::Class, 'userLogout'])->name('logout');


        //write your routes for frontend
        Route::get('/', 'IndexController@index')->name('index');


        // shop route
        Route::get('/shop/{product}', 'ShopController@show')->name('shop.show');
        Route::get('/shop', 'ShopController@index')->name('shop.index');

        // cart route

        Route::get('/cart', 'CartController@index')->name('cart.index');
        Route::post('/cart', 'CartController@store')->name('cart.store');
        Route::get('/cart/{product}', 'CartController@destroy')->name('cart.destroy');
        Route::post('/cart/{product}', 'CartController@update')->name('cart.update');


        ///wish list

        Route::post('/wishlist', 'WishlistController@store')->name('wishlist.store');
        Route::get('/wishlist', 'WishlistController@index')->name('wishlist.index');
        Route::get('/wishlist/{product}', 'WishlistController@destroy')->name('wishlist.destroy');

        //checkout
        Route::get('/checkout', 'CheckoutController@index')->name('checkout.index')->middleware('auth:user');
        Route::post('/checkout', 'CheckoutController@store')->name('checkout.store')->middleware('auth:user');

        // coupon route
        Route::post('/coupon', 'CartController@storeCoupon')->name('coupon.store');
        Route::delete('/coupon', 'CartController@destroyCoupon')->name('coupon.destroy');

        //        review
        Route::post('/review-add', 'ReviewController@store')->name('review.store');
//        newsletter
        Route::post('/newsletter-add', 'IndexController@newsletter')->name('newsletter.add');
        Route::post('/feedback-add', 'IndexController@feedback')->name('feedback.add');


        //my accout

        Route::get('/my-account', 'OrderIndexController@index')->name('my-account')->middleware('auth:user');
        Route::post('/my-account', 'OrderIndexController@store')->name('my-account.store')->middleware('auth:user');

        // password update

app/Coupon.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    public static function findByCode($code){
        return self::where('code', $code)->first();
    }

    public function discount($total)
    {
        if ($this->type == 'fixed') {
            return $this->value;
        }
        else {

            $off = round(( $this->percent_off / 100) * $total);

            return $off;
        }
    }
}

app/Http/Controllers/Backend/CouponController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Coupon;
use App\FeaturedCategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use MercurySeries\Flashy\Flashy;

class CouponController extends Controller
{

    public function index()
    {
        $coupon = Coupon::all();
        return view('backend.pages.coupon.list')->with('coupons',$coupon);
    }

    public function new()
    {
        $coupon = Coupon::all();
        return view('backend.pages.coupon.add')->with('coupons',$coupon);


    }
    public function create(Request $request) {
        $rules = [
            'code' => 'required|unique:coupons',
            'couponType' => 'required'
        ];

        $customMessages = [
//            'name.required' => 'Yo, what should I call you?',
//            'email.required' => 'We need your email address also',
        ];
        $this->validate($request, $rules, $customMessages);
        $coupon = new Coupon();

        $coupon->code = $request->code;
        $coupon->type = $request->couponType;
        $coupon->value = $request->couponValue;
        $coupon->percent_off = $request->couponPercentage;
        $coupon->expire = $request->couponExpireDate;
        $coupon->per_user_limit = $request->couponUserLimit;
        $coupon->max_limit = $request->couponMaxLimit;
        $coupon->minimum_amount = $request->minimum_amount;

        $coupon->save();

        Flashy::success('New Coupon '. $request->couponCode.' created.');
        return redirect()->route('backend.coupon.list');

    }





    public function show($id) {
        //
    }


    public function edit($id)
    {
        $coupon = Coupon::find($id);


        return view('backend.pages.coupon.edit')->with([
            'coupon' => $coupon
        ]);
    }


    public function update(Request $request) {
        $rules = [
            'code' => 'required|unique:coupons,code,'.$request->id,
            'couponType' => 'required'
        ];

        $customMessages = [
//            'name.required' => 'Yo, what should I call you?',
//            'email.required' => 'We need your email address also',
        ];
        $this->validate($request, $rules, $customMessages);
        $coupon = Coupon::find($request->id);

        $coupon->code = $request->code;
        $coupon->type = $request->couponType;
        $coupon->value = $request->couponValue;
        $coupon->percent_off = $request->couponPercentage;
        $coupon->expire = $request->couponExpireDate;
        $coupon->per_user_limit = $request->couponUserLimit;
        $coupon->max_limit = $request->couponMaxLimit;
        $coupon->minimum_amount = $request->minimum_amount;

        $coupon->save();

        Flashy::success('  Coupon '. $request->couponCode.' updated.');

        return redirect()->route('backend.coupon.list');
    }


    public function destroy(Request $request)
    {
        Coupon::find($request->id)->delete();
        Flashy::success('Coupon removed.');
        return back()->with('success_message', 'coupon has been removed.');
    }
}

resources/views/backend/pages/coupon/add.blade.php
@extends('backend.layouts.app')

@section('title', 'New Coupon')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            New Coupon
            <small>Create a new Coupon</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li><a href="#"><i class="fa fa-barcode"></i> Coupon</a></li>
            <li class="active">New Coupon</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content container-fluid">

        <div class="coupon">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <!-- form start -->
                <form class="form-horizontal" action="{{ route('backend.coupon.create') }}" method="post"
                      enctype="multipart/form-data">
                    @csrf
                    <div class="box-body">
                            <div class="form-group">

                            <label for="couponCode" class="col-sm-2 control-label">Coupon Code *</label>

                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="couponCode" name="code" placeholder="New Coupon code.." required>
                                @if ($errors->has('code'))
                                    <span class="text-red" >
                                        <strong>{{ $errors->first('code') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <label for="couponType" class="col-sm-1 control-label">Type</label>

                            <div class="col-sm-3">
                                <select class="form-control " id="couponType" name="couponType">
                                        <option value="fixed">Fixed</option>
                                        <option value="percent_off">Percent Off</option>
                                </select>
                            </div>
                            </div>
                            <div class="form-group">
                                <label for="couponValue" class="col-sm-2 control-label">Discount Amount</label>
                                <div class="col-sm-5">
                                    <input type="number" class="form-control" id="couponValue" name="couponValue" placeholder="For Fixed amout"  >
                                </div>
                                <div class="col-sm-5">
                                    <input type="number" class="form-control" id="couponValue" name="couponPercentage" placeholder="For Percentage discount"  >
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="couponExpire" class="col-sm-2 control-label">Expire Date</label>
                                <div class="col-sm-4">
                                    <input type="date" class="form-control" id="couponExpire" name="couponExpireDate" placeholder="Expire"  >
                                </div>
                                <label for="couponMaxLimit" class="col-sm-2 control-label">Maximum limit</label>

                                <div class="col-sm-4">
                                    <input type="number" class="form-control" id="couponMaxLimit" name="couponMaxLimit" placeholder="" >
                                </div>
                            </div>
                        <div class="form-group">

                            <label for="minimum_amount" class="col-sm-2 control-label">Minimum Amount</label>

                            <div class="col-sm-4">
                                <input type="number" class="form-control" id="minimum_amount" name="minimum_amount" placeholder="" >
                            </div>

                            <label for="couponUserLimit" class="col-sm-2 control-label">Per User limit</label>

                            <div class="col-sm-4">
                                <input type="number" class="form-control" id="couponUserLimit" name="couponUserLimit" placeholder="" >
                            </div>
                        </div>


                    </div>

                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-info pull-right">Create Coupon</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
    </section>

    <section class="container">
        <cite><h5>* Please use unique coupon code name</h5></cite>
        <cite><h5>* For using type Fixed , left for percentage discount blank</h5></cite>
        <cite><h5>* For using type Percentage Off , left for Fixed Amount blank</h5></cite>
        <cite><h5>* For Expire date, Maximum limit, Minimum Amount, Per User limit  unlimited left those blank</h5></cite>
        <br>
        <h5>Coupon's name already active below</h5>
        <table>
            <tr>
            @foreach($coupons as $coupon)
                <li style="list-style-type: none; text-decoration: underline; display: inline; padding-right: 3px" >
                    {{$coupon['code'] }}
                </li>
                @endforeach
            </tr>
        </table>
    </section>

@endsection

resources/views/backend/pages/coupon/edit.blade.php
@extends('backend.layouts.app')

@section('title', 'Coupon Edit')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Edit Coupon
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li><a href="#"><i class="fa fa-barcode"></i> Coupon</a></li>
            <li class="active">Edit Coupon</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content container-fluid">

        <div class="coupon">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <!-- form start -->
                <form class="form-horizontal" action="{{ route('backend.coupon.update') }}" method="post"
                      enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" class="form-control" id="couponCode" name="id"  value="{{ $coupon->id }}">

                    <div class="box-body">
                        <div class="form-group">

                            <label for="couponCode" class="col-sm-2 control-label">Coupon Code *</label>

                            <div class="col-sm-6">
                                <input type="text" class="form-control" id="couponCode" name="code" value="{{ $coupon->code }}" required>

                                @if ($errors->has('code'))
                                    <span class="text-red" >
                                        <strong>{{ $errors->first('code') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <label for="couponType" class="col-sm-1 control-label">Type</label>

                            <div class="col-sm-3">
                                <select class="form-control " id="couponType" name="couponType">

                                    <option {{ $coupon->type=='fixed'? "selected" :""  }} value="fixed">Fixed</option>
                                    <option  {{ $coupon->type=='percent_off'? "selected" :""  }} value="percent_off">Percent Off</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="couponValue" class="col-sm-2 control-label">Discount Amount</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="couponValue" name="couponValue" value="{{ $coupon->value }}"  >
                            </div>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="couponValue" name="couponPercentage"  value="{{ $coupon->percent_off }}" >
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="couponExpire" class="col-sm-2 control-label">Expire Date</label>
                            <div class="col-sm-4">
                                @if($coupon->expire)
                                    <input type="date" class="form-control" id="couponExpire" name="couponExpireDate"   value="{{date('Y-m-d', strtotime($coupon->expire))   }}" >

                                @else
                                    <input type="date" class="form-control" id="couponExpire" name="couponExpireDate"   >

                                @endif

                            </div>
                            <label for="couponMaxLimit" class="col-sm-2 control-label">Maximum limit</label>

                            <div class="col-sm-4">
                                <input type="number" class="form-control" id="couponMaxLimit" name="couponMaxLimit"  value="{{ $coupon->max_limit }}"  >
                            </div>
                        </div>

                        <div class="form-group">


                            <label for="minimum_amount" class="col-sm-2 control-label">Minimum Amount</label>

                            <div class="col-sm-4">
                                <input type="number" class="form-control" id="minimum_amount" name="minimum_amount" value="{{ $coupon->minimum_amount }}" >
                            </div>

                            <label for="couponUserLimit" class="col-sm-2 control-label">Per User limit</label>

                            <div class="col-sm-4">
                                <input type="number" class="form-control" id="couponUserLimit" name="couponUserLimit"  value="{{ $coupon->per_user_limit }}" >
                            </div>
                        </div>
                    </div>

                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-info pull-right">Update Coupon</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
    </section>

    <section class="container">
        <cite><h5>* For using type Fixed , left for percentage discount blank</h5></cite>
        <cite><h5>* For using type Percentage Off , left for Fixed Amount blank</h5></cite>
        <cite><h5>* For Expire date, Maximum limit, Minimum Amount, Per User limit  unlimited left those blank</h5></cite>
        <br>

    </section>


@endsection

resources/views/backend/pages/coupon/list.blade.php
@extends('backend.layouts.app')

@section('title', 'Coupon list')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Coupon
            <small>Coupon list</small>
            <small><a href="{{ route('backend.coupon.add') }}" class="btn btn-success">New Coupon</a></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
            <li class="active">Coupon</li>
        </ol>
    </section>

    <div class="box">
        <!-- /.box-header -->

        <div class="box-body">
            <table id="coupon-list" class="table table-bordered table-striped table-responsive table-hover" >
                <thead>
                <tr>
                    <th>#</th>
                    <th>Coupon code</th>
                    <th>Type</th>
                    <th>Fixed value</th>
                    <th>Percentage value</th>
                    <th>Expired</th>
                    <th>Per user limit</th>
                    <th>Max limit</th>
                    <th>Minimum Amount</th>
                    <th>Created</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($coupons as $coupon)
                    <tr>
                        <td>{{ $coupon->id }}</td>
                        <td>{{ $coupon->code }}</td>

                        @if($coupon->type== "percent_off")
                            <td>Percent Off</td>
                        @else
                            <td>Fixed Amount</td>
                        @endif


                        <td>{{ $coupon->value }}</td>
                        <td>{{ $coupon->percent_off }}</td>
                        @if( $coupon->expire)
                            <td>{{ date('F j, Y, g:i:s a', strtotime($coupon->expire) ) }}</td>
                        @else
                            <td>No expiry</td>
                       @endif

                        @if( $coupon->per_user_limit)
                            <td>{{ $coupon->per_user_limit }}</td>
                        @else
                            <td>No limit</td>
                        @endif
                        @if( $coupon->max_limit)
                            <td>{{ $coupon->max_limit }}</td>
                        @else
                            <td>No limit</td>
                        @endif
                        @if( $coupon->minimum_amount)
                            <td>{{ $coupon->minimum_amount }}</td>
                        @else
                            <td>No Minimum</td>
                        @endif


                        <td>{{ $coupon->created_at }}</td>
                        <td>
                            <a href="{{ route('backend.coupon.edit',['id'=> $coupon->id]) }}"><i class="fa fa-pencil-square fa-lg" style="color:dodgerblue" aria-hidden="true"></i> </a> &nbsp;
                            <a href=""><i class="fa fa-trash fa-lg deletebtn" data-id="{{ $coupon->id }}"
                                          data-name="{{ $coupon->code }}" data-token="{{ @csrf_token() }}" style="color:red"></i> </a>
                        </td>

                    </tr>
                @endforeach

                </tbody>
                <tfoot>
                <tr>
                    <th>#</th>
                    <th>Coupon code</th>
                    <th>Type</th>
                    <th>Fixed value</th>
                    <th>Percentage value</th>
                    <th>Created at</th>
                    <th>Action</th>
                </tr>
                </tfoot>
            </table>

        </div>
    </div>

@endsection

@push('scripts')


    {{-- DataTable js --}}
    <link rel="stylesheet" href="{{asset('backend/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <script src="{{asset('backend/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{asset('backend/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script>
        $(function () {
            $('#coupon-list').DataTable();
            $('.coupon').addClass('active');

        });

        $(document).on('click', '.deletebtn', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var token = $(this).data('token');
            var name = $(this).data('name');
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",

                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: "POST",
                        url: "{{ route('backend.coupon.destroy') }}",
                        data: {id:id, _token:token},
                        success: function (data) {
                            location.reload();
                        }
                    });

                    swal(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                }
            });

        });


    </script>
@endpush